name: Build artifacts
on: [push]

jobs:
  build:
    name: Build on Linux
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ci/build.sh ${{ matrix.os }}
      - name: Commit and Push
        run: |
          git add artifacts
          git commit -am 'ci: update ${{ matrix.os }} artifacts'
          git push origin master
