name: Build artifacts
on: [push]

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ci/build-linux-x86-64.sh
      - name: Commit and Push
        run: >-
          git add artifacts
          git commit -am 'ci: update linux artifacts'
          git push origin master
